#! /usr/bin/env sh

# at least on CentOS 6 the default autotools v2.63
# can't properly include local macros
# instead of autoreconf -i, execute the commands below:

function check_requirement () {
  local readonly REQUIREMENT="${1}"
  local RESULT=0

  if test "x$(command -v ${REQUIREMENT})" = "x"
  then
    echo "missing requirement: ${REQUIREMENT}"
    RESULT=1
  fi

  return ${RESULT}
}

function requirements () {
  local RESULT=0
  check_requirement aclocal || RESULT=1
  check_requirement automake || RESULT=1
  check_requirement autoconf || RESULT=1

  if test "x${RESULT}" = "x1"
  then
    exit 1
  fi
}

function generate () {
  aclocal -I m4
  automake -a -c
  autoconf -I m4
}

function clean () {
  local readonly FILES=" \
    aclocal.m4 \
    autom4te.cache \
    compile \
    components \
    config.guess \
    config.log \
    config.status \
    config.sub \
    configure \
    install-sh \
    localroot \
    Makefile.in \
    Makefile \
    missing \
    tools \
  "
  rm -rf ${FILES}
}

function help () {
  cat << EOF
Usage: bootstrap [-c] [-h]
  Prepare project for configuration.
  Options:
              -c     remove all bootstrap artifacts
              -h     show this help
EOF
}

function main () {
  while getopts ch OPT; do
    case "$OPT" in
      c)
        echo "cleaning bootstrap artifacts"
        clean
        exit 0
        ;;
      h)
        help
        exit 0
        ;;
      \?)
        help
        exit 1
        ;;
    esac
  done

  echo "checking requirements"
  requirements
  echo "bootstrapping the project"
  generate
}

main $@

