#! /usr/bin/env sh

readonly TEMPORARY="$(mktemp -d)"

git init "${TEMPORARY}" || exit 1
git -C "${TEMPORARY}" config --local user.name "Test" || exit 1
git -C "${TEMPORARY}" config --local user.email "Test@test.com" || exit 1
echo "test" > "${TEMPORARY}/test" || exit 1
git -C "${TEMPORARY}" add . || exit 1
git -C "${TEMPORARY}" commit -m "test" || exit 1
git ls-remote --exit-code "${TEMPORARY}" || exit 1

rm -rf "${TEMPORARY}"

