#! /usr/bin/env sh

sudo apt-get update

sudo apt-get install \
  libc6-dev \
  build-essential \
  mingw-w64
  autoconf \
  automake \
  libtool \
  libtool-bin \
  make \
  bison \
  flex \
  gawk \
  git \
  ctags \
  wget \
  ;

